#!/usr/bin/env ruby

# frozen_string_literal: true

require_relative 'lib/data'
require_relative 'lib/loop'
require_relative 'lib/warn'

SlimExplorer.new('watched', 'template.slim', 'scope.yaml').explore
