#!/usr/bin/env ruby

# frozen_string_literal: true

require_relative 'lib/data'
require_relative 'lib/loop'
require_relative 'lib/warn'

SlimExplorer
  .new(
    watched_directory: 'watched',
    slim_template: 'template.slim',
    yaml_file: 'scope.yaml'
  )
  .with_env_vars # Delete this line if you do not want environment name/value pairs in the data
  .with_properties('rabbit': 'bugs bunny')  # Extra tuple just for fun
  .explore
