#chdir: www
daemonize: true
# environment: production
# group: www-data
# log: log/thin.log
max_conns: 1024
# max_persistent_conns: 512
no-epoll: true
# pid: tmp/pids/thin.pid
port: 3030
require: []
servers: 1
#socket: tmp/sockets/thin.sock
tag: rubyThin
threaded: true
timeout: 10
# user: www-data
wait: 10
